### ISSUE TITLE
no function clause matching in MachineGun.Worker.handle_info/2

### ISSUE THREAD

**Issue by 9mm** [petrohi/machine_gun#4]
I put machine_gun under heavy load and started seeing a lot of these. I am not super familiar with Erlang (or elixir) yet so I'm not quite sure where this is originating from.

```
22:45:44.472 [error] Task #PID<0.3139.1> started from #PID<0.3047.1> terminating
** (stop) exited in: GenServer.call(#PID<0.31834.0>, {:request, %MachineGun.Request{body: "", headers: [{"Accept", "*/*"}, {"User-Agent", "Test/1.0"}], method: "GET", path: "/search?feed=xyz"}, #Reference<0.1043175821.4061659137.138797>}, 3000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in MachineGun.Worker.handle_info/2
            (machine_gun) lib/machine_gun/worker.ex:56: MachineGun.Worker.handle_info({:gun_response, #PID<0.31996.0>, #Reference<0.1043175821.4061659138.130077>, :nofin, 200, [{"cache-control", "no-store"}, {"pragma", "no-cache"}, {"age", "0"}, {"content-type", "text/xml; charset=utf-8"}, {"connection", "keep-alive"}, {"content-length", "49"}]}, %MachineGun.Worker{cancels: %{#Reference<0.1043175821.4061659137.138797> => #Reference<0.1043175821.4061659140.138781>}, conn_opts: %{http_opts: %{keepalive: :infinity}, protocols: [:http], retry: 0, transport: :tcp}, gun_pid: #PID<0.7018.1>, gun_ref: #Reference<0.1043175821.4061659140.138780>, host: 'xml.jadspro.live', m_mod: nil, m_state: nil, port: 80, streams: %{#Reference<0.1043175821.4061659140.138781> => {{#PID<0.3139.1>, #Reference<0.1043175821.4061659137.138798>}, %MachineGun.Response{body: nil, headers: nil, request_url: nil, status_code: nil}, #Reference<0.1043175821.4061659137.138797>}}})
            (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
            (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:924: GenServer.call/3
    (machine_gun) lib/machine_gun/worker.ex:26: MachineGun.Worker.request/5
    (poolboy) src/poolboy.erl:76: :poolboy.transaction/3
    (machine_gun) lib/machine_gun.ex:211: MachineGun.do_request/5
    (machine_gun) lib/machine_gun.ex:147: MachineGun.request/5
    (stdlib) timer.erl:166: :timer.tc/1

```

**Comment by petrohi** [comment]
I see the problem. I'll update when fix is ready.
